# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JK' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JK
  pod 'YNDropDownMenu'

  target 'JKTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JKUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
