# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JK' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JK
#  pod 'YNDropDownMenu', :git => 'https://github.com/YakunJin/YNDropDownMenu.git'
pod 'YNDropDownMenu', :path => '../../YNDropDownMenu'
pod 'SMSegmentView'
pod 'collection-view-layouts/Core'
pod 'collection-view-layouts/TagsLayout'
pod 'collection-view-layouts/PinterestLayout'
pod 'collection-view-layouts/Px500Layout'
pod 'collection-view-layouts/InstagramLayout'
pod 'collection-view-layouts/FlipboardLayout'
pod 'collection-view-layouts/FacebookLayout'
pod 'collection-view-layouts/FlickrLayout'

  target 'JKTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JKUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
